import type { Config } from '../types.js';

export function generateRoot(c: Config): Record<string, string> {
  return {
    'package.json': JSON.stringify(
      {
        name: c.name,
        private: true,
        version: '0.0.0',
        description: c.description,
        author: c.author,
        scripts: {
          dev: 'turbo dev',
          build: 'turbo build',
          typecheck: 'turbo typecheck',
          lint: 'turbo lint',
          clean: 'turbo clean',
        },
        packageManager: 'pnpm@9.0.0',
        devDependencies: {
          turbo: '^2.0.0',
          typescript: '^5.5.0',
        },
        pnpm: {
          onlyBuiltDependencies: ['esbuild'],
        },
      },
      null,
      2
    ),

    'pnpm-workspace.yaml': `packages:\n  - 'packages/*'\n  - 'apps/*'\n  - 'examples/*'\n`,

    'turbo.json': JSON.stringify(
      {
        $schema: 'https://turbo.build/schema.json',
        tasks: {
          build: {
            dependsOn: ['^build'],
            outputs: ['dist/**'],
          },
          dev: {
            cache: false,
            persistent: true,
          },
          typecheck: {
            dependsOn: ['^build'],
          },
          clean: {
            cache: false,
          },
        },
      },
      null,
      2
    ),

    'tsconfig.base.json': JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'ESNext',
          moduleResolution: 'bundler',
          strict: true,
          noUncheckedIndexedAccess: true,
          exactOptionalPropertyTypes: true,
          declaration: true,
          skipLibCheck: true,
          esModuleInterop: true,
        },
      },
      null,
      2
    ),

    '.gitignore': [
      'node_modules',
      'dist',
      '.turbo',
      '.env',
      '.env.local',
      '*.tsbuildinfo',
    ].join('\n'),

    '.npmrc': 'shamefully-hoist=false\nstrict-peer-dependencies=false\n',

    'README.md': [
      `# ${c.name}`,
      '',
      'Generated by [create-embed-sdk](https://github.com/your-org/create-embed-sdk).',
      '',
      '## Getting started',
      '',
      '```bash',
      'pnpm install',
      'pnpm dev',
      '```',
      '',
      '## Packages',
      '',
      '| Package | Description |',
      '|---------|-------------|',
      `| \`${c.scope}/protocol\` | Typed message definitions + Zod schemas |`,
      `| \`${c.scope}/core\` | SDK lifecycle engine (FSM, queue, ACK) |`,
      `| \`${c.scope}/loader\` | Tiny IIFE embed.js for script-tag usage |`,
      ...(c.includeReact ? [`| \`${c.scope}/react\` | React hooks + Provider |`] : []),
      '| `widget` | Vite + React iframe app |',
    ].join('\n') + '\n',
  };
}
